# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities import events, context
from langbot_plugin.api.entities.builtin.platform.message import *

import re, random, textwrap


class DefaultEventListener(EventListener):

    def __init__(self):
        super().__init__()
        
        @self.handler(events.GroupMessageReceived)
        async def handler(ctx: context.EventContext):
            msg = str(ctx.event.message_chain).strip()  # 这里的 event 即为 GroupNormalMessageReceived 的对象
            sender_id = ctx.event.sender_id
            if msg == "kcd help":
                self.plugin.init_game()
                await ctx.reply(MessageChain([Plain(text=textwrap.dedent('''
                    项目地址：https://github.com/Garrise/LangBot_Plugin_KCDDiceGame
                    指令列表：
                    kcd help - 查看指令列表
                    kcd start [score] / 玩骰子 [分数] - 开始或加入一局骰子游戏，可以自定义目标积分
                    kcd start badge [score] / 玩徽章骰子 [分数] - 开始一局徽章骰子游戏，可以自定义目标积分
                    kcd badge / 设定徽章 - 查看当前装备的徽章以及徽章列表
                    kcd badge [id] / 设定徽章 [序号] - 设定当前装备的徽章
                    kcd check / 查分 - 查询当前得分
                    kcd score table / - 查询计分表
                    kcd reset / 重置骰子游戏 - 重置骰子游戏
                    ''').strip())]))
            if msg == "重置骰子游戏" or msg =="kcd reset":
                self.plugin.init_game()
                await ctx.reply(MessageChain([Plain(text="骰子游戏已重置。")]))
            if re.match(r"^玩骰子(?:\s\d+)?$", msg) or re.match(r"^kcd start(?:\s\d+)?$", msg):            
                if self.plugin.status == False: #如果游戏尚未开始
                    if msg == "玩骰子" or msg == "kcd start": #默认游戏模式
                        self.plugin.target_score = 1500
                    else:
                        self.plugin.target_score = int(msg.split()[-1])
                    self.plugin.mode = 0
                    self.plugin.status = True
                    self.plugin.player[0] = sender_id
                    self.plugin.dice_lake = []
                    self.plugin.dice_num = 6
                    await ctx.reply(MessageChain([Plain(text=f"{sender_id} 发起了一局骰子游戏邀请，目标分为{self.plugin.target_score}，回复\"玩骰子\"或\"kcd start\"加入游戏。")]))
                    ctx.prevent_default()
                else: #如果游戏已经开始
                    if self.plugin.player[1] == "":
                        if self.plugin.mode == 1 and (not str(sender_id) in self.plugin.player_badges):
                            await ctx.reply(MessageChain([Plain(text=f"{sender_id} 尚未装备徽章，不能加入徽章骰子游戏。")]))
                            ctx.prevent_default()
                        else:
                            self.plugin.player[1] = sender_id
                            self.plugin.score = [0, 0]
                            reply = [f"{sender_id} 加入了骰子游戏，游戏开始!\n\n"]
                            if self.plugin.mode == 1:
                                #金色先行徽章
                                for index, player in enumerate(self.plugin.player):
                                    if self.plugin.player_badges[str(player)] == 4:
                                        self.plugin.score[index] = 1500
                                        reply.append(f"{player} 使用了金制先行徽章，获得1500分！\n\n")
                                #初始化徽章次数
                                self.plugin.init_badges()
                            self.plugin.turn = random.randint(0, 1)
                            await ctx.reply(MessageChain([Plain(text=f"本局游戏由 {self.plugin.player[self.plugin.turn]} 先攻。\n请输入\"投骰\"或\"kcd roll\"进行本回合第一次投骰。")]))
                    else:
                        await ctx.reply(MessageChain([Plain(text="游戏已开始，请等待游戏结束。")]))

            if re.match(r"^玩徽章骰子(?:\s\d+)?$", msg) or re.match(r"^kcd start badge(?:\s\d+)?$", msg):            
                if self.plugin.status == False: #如果游戏尚未开始
                    if not str(sender_id) in self.plugin.player_badges:
                        await ctx.reply(MessageChain([Plain(text=f"{sender_id} 尚未装备徽章，不能发起徽章骰子游戏。")]))
                    else:
                        if msg == "玩徽章骰子" or msg == "kcd start badge": #徽章游戏模式
                            self.plugin.target_score = 5000
                        else:
                            self.plugin.target_score = int(msg.split()[-1])
                        self.plugin.mode = 1
                        self.plugin.status = True
                        self.plugin.player[0] = sender_id
                        self.plugin.dice_lake = []
                        self.plugin.dice_num = 6
                        await ctx.reply(MessageChain([Plain(text=f"{sender_id} 发起了一局徽章骰子游戏邀请，目标分为{self.plugin.target_score}，回复\"玩骰子\"或\"kcd start\"加入游戏。\n要在游戏中使用徽章，请输入\"使用徽章\"或\"kcd use badge\"")]))
                else:
                    await ctx.reply(MessageChain([Plain(text="游戏已开始，请等待游戏结束。")]))

            if re.match(r"^设定徽章(?:\s\d)?$", msg) or re.match(r"^kcd badge(?:\s\d)?$", msg):
                if msg == "设定徽章" or msg == "kcd badge":
                    reply = []
                    if str(sender_id) in self.plugin.player_badges:
                        reply.append(f"{sender_id} 当前装备了{self.plugin.badge_list[self.plugin.player_badges[str(sender_id)]][0]}\n\n")
                    reply.append(textwrap.dedent('''
                        请输入"设定徽章 [序号]"或"kcd badge [id]"来设定装备的徽章，徽章列表如下：
                        1. 金制换点徽章｜投骰后使用，选择任意一颗骰子将其点数更改为１，每局游戏可使用一次
                        2. 金制幸运徽章｜投骰后使用，可以重投最多三颗骰子，每局游戏可使用一次
                        3. 金制力量徽章｜投骰前使用，让这次投骰额外增加一颗骰子，每局游戏可使用三次
                        4. 金制君主徽章｜你的１１１骰子组合获得三倍分数
                        5. 金制先行徽章｜开局时获得１５００分
                        6. 金制镜像徽章｜选择骰子前使用，将你所选骰子的分数翻倍，每局游戏可使用三次
                        7. 金制重投徽章｜投骰后使用，你可以重投所有骰子，每局游戏可使用三次
                        8. 金制军阀徽章｜跳过回合前使用，将本轮分数翻倍，每局游戏可使用一次
                    ''').strip())
                    await ctx.reply(MessageChain([Plain(text=reply)]))
                else:
                    badge_id = int(msg.split()[-1])
                    self.plugin.player_badges[str(sender_id)] = badge_id - 1
                    self.plugin.save_badges() 
                    await ctx.reply(MessageChain([Plain(text=f"{sender_id} 装备了{self.plugin.badge_list[badge_id - 1][0]}")]))

            if re.match(fr"^kcd set [1-6]{{1,{self.plugin.dice_num}}}", msg):
                dices = msg[8:]
                for index, item in enumerate(dices):
                    self.plugin.dice_lake[index] = int(item)
                reply = [self.plugin.build_dice_str()]
                reply.append("\n请输入你希望选择的骰子编号，如果你希望继续投骰，请以\"?\"结尾；如果你希望跳过这回合，请以\"!\"结尾。\n例如，如果你希望选择1，2，3号骰子并跳过，则需要输入\"123!\"\n输入\"计分表\"或\"kcd score table\"以查阅计分表。")
                await ctx.reply(MessageChain([Plain(text=reply)]))
                
            if (msg == "使用徽章" or msg == "kcd use badge") and self.plugin.status == True and self.plugin.mode == 1:
                #检查是否轮到使用者
                if sender_id == self.plugin.player[self.plugin.turn]:
                    #检查徽章使用次数
                    if self.plugin.badge_counts[self.plugin.turn] == 0:
                        await ctx.reply(MessageChain([Plain(text="徽章使用次数为零！")]))
                    else:
                        #1. 金制换点徽章
                        if self.plugin.player_badges[str(sender_id)] == 0:
                            # 检查时点
                            if self.plugin.dice_lake != []:
                                self.wait = 0
                                await ctx.reply(MessageChain([Plain(text="请输入你要替换的骰子编号。")]))
                        #2. 金制幸运徽章
                        elif self.plugin.player_badges[str(sender_id)] == 1:
                            # 检查时点
                            if self.plugin.dice_lake != []:
                                self.wait = 1
                                await ctx.reply(MessageChain([Plain(text="请输入你要重投的骰子编号，最多三位数字，例如：\"235\"。")]))
                        #3. 金制力量徽章
                        elif self.plugin.player_badges[str(sender_id)] == 2:
                            if self.wait == 2:
                                await ctx.reply(MessageChain([Plain(text="每次投骰只能使用一次！")]))
                            else:
                                self.wait = 2
                                self.plugin.dice_num += 1
                                self.plugin.badge_counts[self.plugin.turn] -= 1
                                await ctx.reply(MessageChain([Plain(text=self.plugin.badge_str() + f"\n下一次投骰可以增加一个骰子！")]))
                                ctx.prevent_default()
                        #6. 金制镜像徽章
                        elif self.plugin.player_badges[str(sender_id)] == 5:
                            if self.wait == 5:
                                await ctx.reply(MessageChain([Plain(text="每次选择前只能使用一次！")]))
                            else:
                                self.wait = 5
                                self.plugin.badge_counts[self.plugin.turn] -= 1
                                await ctx.reply(MessageChain([Plain(text=self.plugin.badge_str() + f"\n这次选择的骰子分数翻倍！")]))
                        #7. 金制重投徽章
                        elif self.plugin.player_badges[str(sender_id)] == 6:
                            if self.plugin.dice_lake != []:
                                self.plugin.badge_counts[self.plugin.turn] -= 1
                                success = self.plugin.roll_dice()
                                reply = [self.plugin.badge_str() + "\n\n" + self.plugin.build_dice_str()]
                                if success:
                                    reply.append("\n请输入你希望选择的骰子编号，如果你希望继续投骰，请以\"?\"结尾；如果你希望跳过这回合，请以\"!\"结尾。\n例如，如果你希望选择1，2，3号骰子并跳过，则需要输入\"123!\"\n输入\"计分表\"或\"kcd score table\"以查阅计分表。")
                                else:
                                    reply.append("\n无法得分，本回合投骰作废！")
                                    self.plugin.turn_change()
                                    reply.append(self.plugin.roll_str())
                                await ctx.reply(MessageChain([Plain(text=reply)]))
                                ctx.prevent_default()
                        #8. 金制军阀徽章
                        elif self.plugin.player_badges[str(sender_id)] == 7:
                            if self.wait == 7:
                                await ctx.reply(MessageChain([Plain(text="一回合只能使用一次！")]))
                            else:
                                self.plugin.badge_counts[self.plugin.turn] -= 1
                                self.wait = 7
                                await ctx.reply(MessageChain([Plain(text=self.plugin.badge_str() + f"\n本轮分数翻倍！")]))

            #处理徽章后续操作
            #1. 金制换点徽章
            if re.match(r"^[1-6]$", msg) and sender_id == self.plugin.player[self.plugin.turn] and self.plugin.status == True and self.plugin.mode == 1 and self.wait == 0:
                self.plugin.dice_lake[int(msg) - 1] = 1
                self.plugin.badge_counts[self.plugin.turn] -= 1
                self.wait = -1
                reply = [self.plugin.badge_str() + "\n\n" + self.plugin.build_dice_str()]
                reply.append("\n请输入你希望选择的骰子编号，如果你希望继续投骰，请以\"?\"结尾；如果你希望跳过这回合，请以\"!\"结尾。\n例如，如果你希望选择1，2，3号骰子并跳过，则需要输入\"123!\"\n输入\"计分表\"或\"kcd score table\"以查阅计分表。")
                await ctx.reply(MessageChain([Plain(text=reply)]))
            #2. 金制幸运徽章
            if re.match(r"^(?!.*(.).*\1)[1-6]{1,3}$", msg) and sender_id == self.plugin.player[self.plugin.turn] and self.plugin.status == True and self.plugin.mode == 1 and self.wait == 1:
                success = self.plugin.roll_dice(msg, True)
                self.plugin.badge_counts[self.plugin.turn] -= 1
                self.wait = -1
                reply = [self.plugin.badge_str() + "\n\n" + self.plugin.build_dice_str()]
                if success:
                    reply.append("\n请输入你希望选择的骰子编号，如果你希望继续投骰，请以\"?\"结尾；如果你希望跳过这回合，请以\"!\"结尾。\n例如，如果你希望选择1，2，3号骰子并跳过，则需要输入\"123!\"\n输入\"计分表\"或\"kcd score table\"以查阅计分表。")
                else:
                    reply.append("\n无法得分，本回合投骰作废！")
                    self.plugin.turn_change()
                    reply.append(self.plugin.roll_str())
                await ctx.reply(MessageChain([Plain(text=reply)]))

            if (msg == "投骰" or msg == "kcd roll") and self.plugin.player[self.plugin.turn] == sender_id and self.plugin.status == True: #每回合首次投骰
                success = self.plugin.roll_dice()
                reply = [self.plugin.build_dice_str()]
                if success:
                    reply.append("\n请输入你希望选择的骰子编号，如果你希望继续投骰，请以\"?\"结尾；如果你希望跳过这回合，请以\"!\"结尾。\n例如，如果你希望选择1，2，3号骰子并跳过，则需要输入\"123!\"\n输入\"计分表\"或\"kcd score table\"以查阅计分表。")
                else:
                    #检查重投或换点类徽章
                    if self.plugin.mode == 1 and self.plugin.badge_counts[self.plugin.turn] > 0 and self.plugin.player_badges[str(sender_id)] == 0 or self.plugin.player_badges[str(sender_id)] == 1 or self.plugin.player_badges[str(sender_id)] == 6:
                        reply.append(f"\n无法得分，你可以使用{self.plugin.badge_list[self.plugin.player_badges[str(sender_id)]][0]}！不使用请输入\"!\"跳过")
                        self.wait = -2
                    else:
                        reply.append("\n无法得分，本回合投骰作废！")
                        self.plugin.turn_change()
                        reply.append(self.plugin.roll_str())
                await ctx.reply(MessageChain([Plain(text=reply)]))

            if msg == "!" and self.wait == -2 and sender_id == self.plugin.player[self.plugin.turn] and self.plugin.status == True:
                reply = ["本回合投骰作废！"]
                self.plugin.turn_change()
                reply.append(self.plugin.roll_str())
                await ctx.reply(MessageChain([Plain(text=reply)]))
            
            if (msg == "查分" or msg == "kcd check") and self.plugin.status == True:
                for index, item in enumerate(self.plugin.player):
                    if item == sender_id:
                        await ctx.reply(MessageChain([Plain(text=f"{item} 当前得分为{self.plugin.score[index]}")]))
            
            if msg == "计分表" or msg == "kcd score table":
                await ctx.reply(MessageChain([Plain(text="""
                    　规则类型｜　　骰子组合｜分数
                    ————————————————
                    单骰子得分｜　　　　　１｜１００
                    　　　　　｜　　　　　５｜５０
                    ————————————————
                    　顺子得分｜１２３４５６｜１５００
                    　　　　　｜　１２３４５｜５００
                    　　　　　｜　２３４５６｜７５０
                    ————————————————
                    同点数得分｜　　　１１１｜１０００
                    　　　　　｜　　　２２２｜２００
                    　　　　　｜　　　３３３｜３００
                    　　　　　｜　　　４４４｜４００
                    　　　　　｜　　　５５５｜５００
                    　　　　　｜　　　６６６｜６００
                    ————————————————
                    同点数递增｜　　２２２２｜４００
                    每一个额外｜　２２２２２｜８００
                    分数翻一倍｜２２２２２２｜１６００
                    """.strip())]))

            if re.match(fr"^(?!.*(.).*\1)[1-{self.plugin.dice_num}]{{1,{self.plugin.dice_num}}}[!?]$", msg) and self.plugin.status == True: #每回合后续算分并投骰
                if self.plugin.player[self.plugin.turn] == sender_id:
                    dice_ids = []
                    next = False
                    if msg[-1] == "!":
                        next = False
                    elif msg[-1] == "?":
                        next = True
                    dice_str = msg[:-1]
                    for char in dice_str:
                        dice_ids.append(int(char))
                    score = self.plugin.score_calculate(self.plugin.dice_calculate(dice_ids))
                    if score == 0:
                        await ctx.reply(MessageChain([Plain(text="分数为零，请重新选择。")]))
                    else: #算分有效，计入本回合积分，去除使用过的骰子，并判断是否继续投骰
                        #金制镜像徽章
                        if self.plugin.mode == 1:
                            if self.plugin.player_badges[str(sender_id)] == 5 and self.wait == 5:
                                self.plugin.temp_score += 2 * score
                                self.wait = -1
                            else:
                                self.plugin.temp_score += score
                        else:
                            self.plugin.temp_score += score
                        self.plugin.dice_num -= len(dice_str)
                        reply = []
                        if self.archlord:
                            self.archlord = False
                            reply.append(f"{sender_id} 触发了金制君主徽章！\n\n")
                        if self.plugin.dice_num == 0:
                            self.plugin.dice_num = 6
                        if next: #继续投骰
                            success = self.plugin.roll_dice()
                            reply.append(self.plugin.build_dice_str())
                            if success:
                                reply.append("\n请输入你希望选择的骰子编号，如果你希望继续投骰，请以\"?\"结尾；如果你希望跳过这回合，请以\"!\"结尾。\n例如，如果你希望选择1，2，3号骰子并跳过，则需要输入\"123!\"")
                            else:
                                #检查重投或换点类徽章
                                if self.plugin.mode == 1:
                                    if self.plugin.badge_counts[self.plugin.turn] > 0 and self.plugin.player_badges[str(sender_id)] == 0 or self.plugin.player_badges[str(sender_id)] == 1 or self.plugin.player_badges[str(sender_id)] == 6:
                                        reply.append(f"\n无法得分，你可以使用{self.plugin.badge_list[self.plugin.player_badges[str(sender_id)]][0]}！不使用请输入\"!\"跳过")
                                        self.wait = -2
                                    else:
                                        reply.append("\n无法得分，本回合投骰作废！")
                                        self.plugin.turn_change()
                                        reply.append(self.plugin.roll_str())
                                else:
                                    reply.append("\n无法得分，本回合投骰作废！")
                                    self.plugin.turn_change()
                                    reply.append(self.plugin.roll_str())
                            await ctx.reply(MessageChain([Plain(text=reply)]))
                        else: #跳过投骰，将本回合积分加入总分，切换回合
                            #金制军阀徽章
                            reply = []
                            if self.plugin.mode == 1:
                                if self.plugin.player_badges[str(sender_id)] == 7 and self.wait == 7:
                                    self.plugin.score[self.plugin.turn] += 2 * self.plugin.temp_score
                                    reply.append(f"{self.plugin.player[self.plugin.turn]} 的回合得分为{2 * self.plugin.temp_score}分。")
                                    self.wait = -1
                                else:
                                    self.plugin.score[self.plugin.turn] += self.plugin.temp_score
                                    reply.append(f"{self.plugin.player[self.plugin.turn]} 的回合得分为{self.plugin.temp_score}分。")
                            else:
                                self.plugin.score[self.plugin.turn] += self.plugin.temp_score
                                reply.append(f"{self.plugin.player[self.plugin.turn]} 的回合得分为{self.plugin.temp_score}分。")
                            reply.append(f"目前总分为{self.plugin.score[self.plugin.turn]}。")
                            if self.plugin.score[self.plugin.turn] >= self.plugin.target_score:
                                reply.append(f"{self.plugin.player[self.plugin.turn]} 赢得了胜利！")
                                self.plugin.init_game()
                            else:
                                self.plugin.turn_change()
                                reply.append(self.plugin.roll_str())
                            await ctx.reply(MessageChain([Plain(text=reply)]))